plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    signingConfigs {
        debug {
            storeFile file('D:\\Android\\Bloqueador_de_chamadas\\Keystore\\keystore.jks')
            storePassword RELEASE_STORE_PASSWORD
            keyPassword RELEASE_KEY_PASSWORD
            keyAlias RELEASE_KEY_ALIAS
        }
        release {
            storeFile file('D:\\Android\\Bloqueador_de_chamadas\\Keystore\\keystore.jks')
            storePassword RELEASE_STORE_PASSWORD
            keyPassword RELEASE_KEY_PASSWORD
            keyAlias RELEASE_KEY_ALIAS
        }
    }
    namespace 'com.bloqueadordechamadas'
    compileSdk 37

    defaultConfig {
        applicationId "com.bloqueadordechamadas"
        minSdk 26
        targetSdk 37
        versionCode 3
        versionName "1.2"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    lint {
        checkReleaseBuilds false
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildToolsVersion buildToolsVersion
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.recyclerview
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    implementation platform(libs.firebase.bom)
    implementation libs.firebase.analytics
}
